### ISSUE TITLE
Quick Play Splits

### ISSUE THREAD

**Issue by ZaptorZap** [Founntain/TetraLeague.Overlay#4]
You can get floor split times off the API at `.data.best.record.results.stats.zenith.splits[]` or `.data.record.record.results.stats.zenith.splits[]` (may not exist if they haven't played this week) in <https://ch.tetr.io/api/users/USER/summaries/zenith>(/zenithex). These are just splits for their best or PB run, not their best/PB splits of all time, so if you want to track that, unfortunately you would have to roll your own database for that. You can quickly iterate over all of their runs this week, but that would still be a limited dataset.

**Comment by Founntain** [comment]
Thanks for noting that stuff down from the stream. Will be interessting todo.

**Comment by Founntain** [comment]
done
